
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ArticleAuthor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ArticleAuthor
 * 
 */
export type ArticleAuthorModel = runtime.Types.Result.DefaultSelection<Prisma.$ArticleAuthorPayload>

export type AggregateArticleAuthor = {
  _count: ArticleAuthorCountAggregateOutputType | null
  _min: ArticleAuthorMinAggregateOutputType | null
  _max: ArticleAuthorMaxAggregateOutputType | null
}

export type ArticleAuthorMinAggregateOutputType = {
  id: string | null
  articleId: string | null
  authorId: string | null
  role: string | null
  status: string | null
}

export type ArticleAuthorMaxAggregateOutputType = {
  id: string | null
  articleId: string | null
  authorId: string | null
  role: string | null
  status: string | null
}

export type ArticleAuthorCountAggregateOutputType = {
  id: number
  articleId: number
  authorId: number
  role: number
  status: number
  _all: number
}


export type ArticleAuthorMinAggregateInputType = {
  id?: true
  articleId?: true
  authorId?: true
  role?: true
  status?: true
}

export type ArticleAuthorMaxAggregateInputType = {
  id?: true
  articleId?: true
  authorId?: true
  role?: true
  status?: true
}

export type ArticleAuthorCountAggregateInputType = {
  id?: true
  articleId?: true
  authorId?: true
  role?: true
  status?: true
  _all?: true
}

export type ArticleAuthorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArticleAuthor to aggregate.
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArticleAuthors to fetch.
   */
  orderBy?: Prisma.ArticleAuthorOrderByWithRelationInput | Prisma.ArticleAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ArticleAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArticleAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArticleAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ArticleAuthors
  **/
  _count?: true | ArticleAuthorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ArticleAuthorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ArticleAuthorMaxAggregateInputType
}

export type GetArticleAuthorAggregateType<T extends ArticleAuthorAggregateArgs> = {
      [P in keyof T & keyof AggregateArticleAuthor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateArticleAuthor[P]>
    : Prisma.GetScalarType<T[P], AggregateArticleAuthor[P]>
}




export type ArticleAuthorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArticleAuthorWhereInput
  orderBy?: Prisma.ArticleAuthorOrderByWithAggregationInput | Prisma.ArticleAuthorOrderByWithAggregationInput[]
  by: Prisma.ArticleAuthorScalarFieldEnum[] | Prisma.ArticleAuthorScalarFieldEnum
  having?: Prisma.ArticleAuthorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ArticleAuthorCountAggregateInputType | true
  _min?: ArticleAuthorMinAggregateInputType
  _max?: ArticleAuthorMaxAggregateInputType
}

export type ArticleAuthorGroupByOutputType = {
  id: string
  articleId: string
  authorId: string
  role: string
  status: string
  _count: ArticleAuthorCountAggregateOutputType | null
  _min: ArticleAuthorMinAggregateOutputType | null
  _max: ArticleAuthorMaxAggregateOutputType | null
}

export type GetArticleAuthorGroupByPayload<T extends ArticleAuthorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ArticleAuthorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ArticleAuthorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ArticleAuthorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ArticleAuthorGroupByOutputType[P]>
      }
    >
  >



export type ArticleAuthorWhereInput = {
  AND?: Prisma.ArticleAuthorWhereInput | Prisma.ArticleAuthorWhereInput[]
  OR?: Prisma.ArticleAuthorWhereInput[]
  NOT?: Prisma.ArticleAuthorWhereInput | Prisma.ArticleAuthorWhereInput[]
  id?: Prisma.StringFilter<"ArticleAuthor"> | string
  articleId?: Prisma.StringFilter<"ArticleAuthor"> | string
  authorId?: Prisma.StringFilter<"ArticleAuthor"> | string
  role?: Prisma.StringFilter<"ArticleAuthor"> | string
  status?: Prisma.StringFilter<"ArticleAuthor"> | string
}

export type ArticleAuthorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ArticleAuthorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ArticleAuthorWhereInput | Prisma.ArticleAuthorWhereInput[]
  OR?: Prisma.ArticleAuthorWhereInput[]
  NOT?: Prisma.ArticleAuthorWhereInput | Prisma.ArticleAuthorWhereInput[]
  articleId?: Prisma.StringFilter<"ArticleAuthor"> | string
  authorId?: Prisma.StringFilter<"ArticleAuthor"> | string
  role?: Prisma.StringFilter<"ArticleAuthor"> | string
  status?: Prisma.StringFilter<"ArticleAuthor"> | string
}, "id">

export type ArticleAuthorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.ArticleAuthorCountOrderByAggregateInput
  _max?: Prisma.ArticleAuthorMaxOrderByAggregateInput
  _min?: Prisma.ArticleAuthorMinOrderByAggregateInput
}

export type ArticleAuthorScalarWhereWithAggregatesInput = {
  AND?: Prisma.ArticleAuthorScalarWhereWithAggregatesInput | Prisma.ArticleAuthorScalarWhereWithAggregatesInput[]
  OR?: Prisma.ArticleAuthorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ArticleAuthorScalarWhereWithAggregatesInput | Prisma.ArticleAuthorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ArticleAuthor"> | string
  articleId?: Prisma.StringWithAggregatesFilter<"ArticleAuthor"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"ArticleAuthor"> | string
  role?: Prisma.StringWithAggregatesFilter<"ArticleAuthor"> | string
  status?: Prisma.StringWithAggregatesFilter<"ArticleAuthor"> | string
}

export type ArticleAuthorCreateInput = {
  id?: string
  articleId: string
  authorId: string
  role: string
  status: string
}

export type ArticleAuthorUncheckedCreateInput = {
  id?: string
  articleId: string
  authorId: string
  role: string
  status: string
}

export type ArticleAuthorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArticleAuthorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArticleAuthorCreateManyInput = {
  id?: string
  articleId: string
  authorId: string
  role: string
  status: string
}

export type ArticleAuthorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArticleAuthorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ArticleAuthorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ArticleAuthorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ArticleAuthorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  status?: Prisma.SortOrder
}



export type ArticleAuthorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  articleId?: boolean
  authorId?: boolean
  role?: boolean
  status?: boolean
}, ExtArgs["result"]["articleAuthor"]>

export type ArticleAuthorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  articleId?: boolean
  authorId?: boolean
  role?: boolean
  status?: boolean
}, ExtArgs["result"]["articleAuthor"]>

export type ArticleAuthorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  articleId?: boolean
  authorId?: boolean
  role?: boolean
  status?: boolean
}, ExtArgs["result"]["articleAuthor"]>

export type ArticleAuthorSelectScalar = {
  id?: boolean
  articleId?: boolean
  authorId?: boolean
  role?: boolean
  status?: boolean
}

export type ArticleAuthorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "articleId" | "authorId" | "role" | "status", ExtArgs["result"]["articleAuthor"]>

export type $ArticleAuthorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ArticleAuthor"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    articleId: string
    authorId: string
    role: string
    status: string
  }, ExtArgs["result"]["articleAuthor"]>
  composites: {}
}

export type ArticleAuthorGetPayload<S extends boolean | null | undefined | ArticleAuthorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload, S>

export type ArticleAuthorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ArticleAuthorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ArticleAuthorCountAggregateInputType | true
  }

export interface ArticleAuthorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ArticleAuthor'], meta: { name: 'ArticleAuthor' } }
  /**
   * Find zero or one ArticleAuthor that matches the filter.
   * @param {ArticleAuthorFindUniqueArgs} args - Arguments to find a ArticleAuthor
   * @example
   * // Get one ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ArticleAuthorFindUniqueArgs>(args: Prisma.SelectSubset<T, ArticleAuthorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ArticleAuthor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ArticleAuthorFindUniqueOrThrowArgs} args - Arguments to find a ArticleAuthor
   * @example
   * // Get one ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ArticleAuthorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ArticleAuthorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArticleAuthor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorFindFirstArgs} args - Arguments to find a ArticleAuthor
   * @example
   * // Get one ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ArticleAuthorFindFirstArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorFindFirstArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArticleAuthor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorFindFirstOrThrowArgs} args - Arguments to find a ArticleAuthor
   * @example
   * // Get one ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ArticleAuthorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ArticleAuthors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ArticleAuthors
   * const articleAuthors = await prisma.articleAuthor.findMany()
   * 
   * // Get first 10 ArticleAuthors
   * const articleAuthors = await prisma.articleAuthor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const articleAuthorWithIdOnly = await prisma.articleAuthor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ArticleAuthorFindManyArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ArticleAuthor.
   * @param {ArticleAuthorCreateArgs} args - Arguments to create a ArticleAuthor.
   * @example
   * // Create one ArticleAuthor
   * const ArticleAuthor = await prisma.articleAuthor.create({
   *   data: {
   *     // ... data to create a ArticleAuthor
   *   }
   * })
   * 
   */
  create<T extends ArticleAuthorCreateArgs>(args: Prisma.SelectSubset<T, ArticleAuthorCreateArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ArticleAuthors.
   * @param {ArticleAuthorCreateManyArgs} args - Arguments to create many ArticleAuthors.
   * @example
   * // Create many ArticleAuthors
   * const articleAuthor = await prisma.articleAuthor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ArticleAuthorCreateManyArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ArticleAuthors and returns the data saved in the database.
   * @param {ArticleAuthorCreateManyAndReturnArgs} args - Arguments to create many ArticleAuthors.
   * @example
   * // Create many ArticleAuthors
   * const articleAuthor = await prisma.articleAuthor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ArticleAuthors and only return the `id`
   * const articleAuthorWithIdOnly = await prisma.articleAuthor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ArticleAuthorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ArticleAuthor.
   * @param {ArticleAuthorDeleteArgs} args - Arguments to delete one ArticleAuthor.
   * @example
   * // Delete one ArticleAuthor
   * const ArticleAuthor = await prisma.articleAuthor.delete({
   *   where: {
   *     // ... filter to delete one ArticleAuthor
   *   }
   * })
   * 
   */
  delete<T extends ArticleAuthorDeleteArgs>(args: Prisma.SelectSubset<T, ArticleAuthorDeleteArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ArticleAuthor.
   * @param {ArticleAuthorUpdateArgs} args - Arguments to update one ArticleAuthor.
   * @example
   * // Update one ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ArticleAuthorUpdateArgs>(args: Prisma.SelectSubset<T, ArticleAuthorUpdateArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ArticleAuthors.
   * @param {ArticleAuthorDeleteManyArgs} args - Arguments to filter ArticleAuthors to delete.
   * @example
   * // Delete a few ArticleAuthors
   * const { count } = await prisma.articleAuthor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ArticleAuthorDeleteManyArgs>(args?: Prisma.SelectSubset<T, ArticleAuthorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArticleAuthors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ArticleAuthors
   * const articleAuthor = await prisma.articleAuthor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ArticleAuthorUpdateManyArgs>(args: Prisma.SelectSubset<T, ArticleAuthorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArticleAuthors and returns the data updated in the database.
   * @param {ArticleAuthorUpdateManyAndReturnArgs} args - Arguments to update many ArticleAuthors.
   * @example
   * // Update many ArticleAuthors
   * const articleAuthor = await prisma.articleAuthor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ArticleAuthors and only return the `id`
   * const articleAuthorWithIdOnly = await prisma.articleAuthor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ArticleAuthorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ArticleAuthorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ArticleAuthor.
   * @param {ArticleAuthorUpsertArgs} args - Arguments to update or create a ArticleAuthor.
   * @example
   * // Update or create a ArticleAuthor
   * const articleAuthor = await prisma.articleAuthor.upsert({
   *   create: {
   *     // ... data to create a ArticleAuthor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ArticleAuthor we want to update
   *   }
   * })
   */
  upsert<T extends ArticleAuthorUpsertArgs>(args: Prisma.SelectSubset<T, ArticleAuthorUpsertArgs<ExtArgs>>): Prisma.Prisma__ArticleAuthorClient<runtime.Types.Result.GetResult<Prisma.$ArticleAuthorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ArticleAuthors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorCountArgs} args - Arguments to filter ArticleAuthors to count.
   * @example
   * // Count the number of ArticleAuthors
   * const count = await prisma.articleAuthor.count({
   *   where: {
   *     // ... the filter for the ArticleAuthors we want to count
   *   }
   * })
  **/
  count<T extends ArticleAuthorCountArgs>(
    args?: Prisma.Subset<T, ArticleAuthorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ArticleAuthorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ArticleAuthor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ArticleAuthorAggregateArgs>(args: Prisma.Subset<T, ArticleAuthorAggregateArgs>): Prisma.PrismaPromise<GetArticleAuthorAggregateType<T>>

  /**
   * Group by ArticleAuthor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArticleAuthorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ArticleAuthorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ArticleAuthorGroupByArgs['orderBy'] }
      : { orderBy?: ArticleAuthorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ArticleAuthorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetArticleAuthorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ArticleAuthor model
 */
readonly fields: ArticleAuthorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ArticleAuthor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ArticleAuthorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ArticleAuthor model
 */
export interface ArticleAuthorFieldRefs {
  readonly id: Prisma.FieldRef<"ArticleAuthor", 'String'>
  readonly articleId: Prisma.FieldRef<"ArticleAuthor", 'String'>
  readonly authorId: Prisma.FieldRef<"ArticleAuthor", 'String'>
  readonly role: Prisma.FieldRef<"ArticleAuthor", 'String'>
  readonly status: Prisma.FieldRef<"ArticleAuthor", 'String'>
}
    

// Custom InputTypes
/**
 * ArticleAuthor findUnique
 */
export type ArticleAuthorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter, which ArticleAuthor to fetch.
   */
  where: Prisma.ArticleAuthorWhereUniqueInput
}

/**
 * ArticleAuthor findUniqueOrThrow
 */
export type ArticleAuthorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter, which ArticleAuthor to fetch.
   */
  where: Prisma.ArticleAuthorWhereUniqueInput
}

/**
 * ArticleAuthor findFirst
 */
export type ArticleAuthorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter, which ArticleAuthor to fetch.
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArticleAuthors to fetch.
   */
  orderBy?: Prisma.ArticleAuthorOrderByWithRelationInput | Prisma.ArticleAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArticleAuthors.
   */
  cursor?: Prisma.ArticleAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArticleAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArticleAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArticleAuthors.
   */
  distinct?: Prisma.ArticleAuthorScalarFieldEnum | Prisma.ArticleAuthorScalarFieldEnum[]
}

/**
 * ArticleAuthor findFirstOrThrow
 */
export type ArticleAuthorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter, which ArticleAuthor to fetch.
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArticleAuthors to fetch.
   */
  orderBy?: Prisma.ArticleAuthorOrderByWithRelationInput | Prisma.ArticleAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArticleAuthors.
   */
  cursor?: Prisma.ArticleAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArticleAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArticleAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArticleAuthors.
   */
  distinct?: Prisma.ArticleAuthorScalarFieldEnum | Prisma.ArticleAuthorScalarFieldEnum[]
}

/**
 * ArticleAuthor findMany
 */
export type ArticleAuthorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter, which ArticleAuthors to fetch.
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArticleAuthors to fetch.
   */
  orderBy?: Prisma.ArticleAuthorOrderByWithRelationInput | Prisma.ArticleAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ArticleAuthors.
   */
  cursor?: Prisma.ArticleAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArticleAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArticleAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArticleAuthors.
   */
  distinct?: Prisma.ArticleAuthorScalarFieldEnum | Prisma.ArticleAuthorScalarFieldEnum[]
}

/**
 * ArticleAuthor create
 */
export type ArticleAuthorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * The data needed to create a ArticleAuthor.
   */
  data: Prisma.XOR<Prisma.ArticleAuthorCreateInput, Prisma.ArticleAuthorUncheckedCreateInput>
}

/**
 * ArticleAuthor createMany
 */
export type ArticleAuthorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ArticleAuthors.
   */
  data: Prisma.ArticleAuthorCreateManyInput | Prisma.ArticleAuthorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ArticleAuthor createManyAndReturn
 */
export type ArticleAuthorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * The data used to create many ArticleAuthors.
   */
  data: Prisma.ArticleAuthorCreateManyInput | Prisma.ArticleAuthorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ArticleAuthor update
 */
export type ArticleAuthorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * The data needed to update a ArticleAuthor.
   */
  data: Prisma.XOR<Prisma.ArticleAuthorUpdateInput, Prisma.ArticleAuthorUncheckedUpdateInput>
  /**
   * Choose, which ArticleAuthor to update.
   */
  where: Prisma.ArticleAuthorWhereUniqueInput
}

/**
 * ArticleAuthor updateMany
 */
export type ArticleAuthorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ArticleAuthors.
   */
  data: Prisma.XOR<Prisma.ArticleAuthorUpdateManyMutationInput, Prisma.ArticleAuthorUncheckedUpdateManyInput>
  /**
   * Filter which ArticleAuthors to update
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * Limit how many ArticleAuthors to update.
   */
  limit?: number
}

/**
 * ArticleAuthor updateManyAndReturn
 */
export type ArticleAuthorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * The data used to update ArticleAuthors.
   */
  data: Prisma.XOR<Prisma.ArticleAuthorUpdateManyMutationInput, Prisma.ArticleAuthorUncheckedUpdateManyInput>
  /**
   * Filter which ArticleAuthors to update
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * Limit how many ArticleAuthors to update.
   */
  limit?: number
}

/**
 * ArticleAuthor upsert
 */
export type ArticleAuthorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * The filter to search for the ArticleAuthor to update in case it exists.
   */
  where: Prisma.ArticleAuthorWhereUniqueInput
  /**
   * In case the ArticleAuthor found by the `where` argument doesn't exist, create a new ArticleAuthor with this data.
   */
  create: Prisma.XOR<Prisma.ArticleAuthorCreateInput, Prisma.ArticleAuthorUncheckedCreateInput>
  /**
   * In case the ArticleAuthor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ArticleAuthorUpdateInput, Prisma.ArticleAuthorUncheckedUpdateInput>
}

/**
 * ArticleAuthor delete
 */
export type ArticleAuthorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
  /**
   * Filter which ArticleAuthor to delete.
   */
  where: Prisma.ArticleAuthorWhereUniqueInput
}

/**
 * ArticleAuthor deleteMany
 */
export type ArticleAuthorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArticleAuthors to delete
   */
  where?: Prisma.ArticleAuthorWhereInput
  /**
   * Limit how many ArticleAuthors to delete.
   */
  limit?: number
}

/**
 * ArticleAuthor without action
 */
export type ArticleAuthorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArticleAuthor
   */
  select?: Prisma.ArticleAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArticleAuthor
   */
  omit?: Prisma.ArticleAuthorOmit<ExtArgs> | null
}
