
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthzRole` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AuthzRole
 * 
 */
export type AuthzRoleModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthzRolePayload>

export type AggregateAuthzRole = {
  _count: AuthzRoleCountAggregateOutputType | null
  _min: AuthzRoleMinAggregateOutputType | null
  _max: AuthzRoleMaxAggregateOutputType | null
}

export type AuthzRoleMinAggregateOutputType = {
  id: string | null
  name: string | null
  syncedOn: Date | null
}

export type AuthzRoleMaxAggregateOutputType = {
  id: string | null
  name: string | null
  syncedOn: Date | null
}

export type AuthzRoleCountAggregateOutputType = {
  id: number
  name: number
  permissions: number
  syncedOn: number
  _all: number
}


export type AuthzRoleMinAggregateInputType = {
  id?: true
  name?: true
  syncedOn?: true
}

export type AuthzRoleMaxAggregateInputType = {
  id?: true
  name?: true
  syncedOn?: true
}

export type AuthzRoleCountAggregateInputType = {
  id?: true
  name?: true
  permissions?: true
  syncedOn?: true
  _all?: true
}

export type AuthzRoleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthzRole to aggregate.
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzRoles to fetch.
   */
  orderBy?: Prisma.AuthzRoleOrderByWithRelationInput | Prisma.AuthzRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthzRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthzRoles
  **/
  _count?: true | AuthzRoleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthzRoleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthzRoleMaxAggregateInputType
}

export type GetAuthzRoleAggregateType<T extends AuthzRoleAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthzRole]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthzRole[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthzRole[P]>
}




export type AuthzRoleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthzRoleWhereInput
  orderBy?: Prisma.AuthzRoleOrderByWithAggregationInput | Prisma.AuthzRoleOrderByWithAggregationInput[]
  by: Prisma.AuthzRoleScalarFieldEnum[] | Prisma.AuthzRoleScalarFieldEnum
  having?: Prisma.AuthzRoleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthzRoleCountAggregateInputType | true
  _min?: AuthzRoleMinAggregateInputType
  _max?: AuthzRoleMaxAggregateInputType
}

export type AuthzRoleGroupByOutputType = {
  id: string
  name: string
  permissions: runtime.JsonValue | null
  syncedOn: Date
  _count: AuthzRoleCountAggregateOutputType | null
  _min: AuthzRoleMinAggregateOutputType | null
  _max: AuthzRoleMaxAggregateOutputType | null
}

export type GetAuthzRoleGroupByPayload<T extends AuthzRoleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthzRoleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthzRoleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthzRoleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthzRoleGroupByOutputType[P]>
      }
    >
  >



export type AuthzRoleWhereInput = {
  AND?: Prisma.AuthzRoleWhereInput | Prisma.AuthzRoleWhereInput[]
  OR?: Prisma.AuthzRoleWhereInput[]
  NOT?: Prisma.AuthzRoleWhereInput | Prisma.AuthzRoleWhereInput[]
  id?: Prisma.StringFilter<"AuthzRole"> | string
  name?: Prisma.StringFilter<"AuthzRole"> | string
  permissions?: Prisma.JsonNullableFilter<"AuthzRole">
  syncedOn?: Prisma.DateTimeFilter<"AuthzRole"> | Date | string
}

export type AuthzRoleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  syncedOn?: Prisma.SortOrder
}

export type AuthzRoleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuthzRoleWhereInput | Prisma.AuthzRoleWhereInput[]
  OR?: Prisma.AuthzRoleWhereInput[]
  NOT?: Prisma.AuthzRoleWhereInput | Prisma.AuthzRoleWhereInput[]
  name?: Prisma.StringFilter<"AuthzRole"> | string
  permissions?: Prisma.JsonNullableFilter<"AuthzRole">
  syncedOn?: Prisma.DateTimeFilter<"AuthzRole"> | Date | string
}, "id">

export type AuthzRoleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  syncedOn?: Prisma.SortOrder
  _count?: Prisma.AuthzRoleCountOrderByAggregateInput
  _max?: Prisma.AuthzRoleMaxOrderByAggregateInput
  _min?: Prisma.AuthzRoleMinOrderByAggregateInput
}

export type AuthzRoleScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthzRoleScalarWhereWithAggregatesInput | Prisma.AuthzRoleScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthzRoleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthzRoleScalarWhereWithAggregatesInput | Prisma.AuthzRoleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthzRole"> | string
  name?: Prisma.StringWithAggregatesFilter<"AuthzRole"> | string
  permissions?: Prisma.JsonNullableWithAggregatesFilter<"AuthzRole">
  syncedOn?: Prisma.DateTimeWithAggregatesFilter<"AuthzRole"> | Date | string
}

export type AuthzRoleCreateInput = {
  id?: string
  name: string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Date | string
}

export type AuthzRoleUncheckedCreateInput = {
  id?: string
  name: string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Date | string
}

export type AuthzRoleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthzRoleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthzRoleCreateManyInput = {
  id?: string
  name: string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Date | string
}

export type AuthzRoleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthzRoleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  syncedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthzRoleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  syncedOn?: Prisma.SortOrder
}

export type AuthzRoleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  syncedOn?: Prisma.SortOrder
}

export type AuthzRoleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  syncedOn?: Prisma.SortOrder
}



export type AuthzRoleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  permissions?: boolean
  syncedOn?: boolean
}, ExtArgs["result"]["authzRole"]>

export type AuthzRoleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  permissions?: boolean
  syncedOn?: boolean
}, ExtArgs["result"]["authzRole"]>

export type AuthzRoleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  permissions?: boolean
  syncedOn?: boolean
}, ExtArgs["result"]["authzRole"]>

export type AuthzRoleSelectScalar = {
  id?: boolean
  name?: boolean
  permissions?: boolean
  syncedOn?: boolean
}

export type AuthzRoleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "permissions" | "syncedOn", ExtArgs["result"]["authzRole"]>

export type $AuthzRolePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthzRole"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    permissions: runtime.JsonValue | null
    syncedOn: Date
  }, ExtArgs["result"]["authzRole"]>
  composites: {}
}

export type AuthzRoleGetPayload<S extends boolean | null | undefined | AuthzRoleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload, S>

export type AuthzRoleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthzRoleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthzRoleCountAggregateInputType | true
  }

export interface AuthzRoleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthzRole'], meta: { name: 'AuthzRole' } }
  /**
   * Find zero or one AuthzRole that matches the filter.
   * @param {AuthzRoleFindUniqueArgs} args - Arguments to find a AuthzRole
   * @example
   * // Get one AuthzRole
   * const authzRole = await prisma.authzRole.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthzRoleFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthzRoleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthzRole that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthzRoleFindUniqueOrThrowArgs} args - Arguments to find a AuthzRole
   * @example
   * // Get one AuthzRole
   * const authzRole = await prisma.authzRole.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthzRoleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthzRoleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthzRole that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleFindFirstArgs} args - Arguments to find a AuthzRole
   * @example
   * // Get one AuthzRole
   * const authzRole = await prisma.authzRole.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthzRoleFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthzRoleFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthzRole that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleFindFirstOrThrowArgs} args - Arguments to find a AuthzRole
   * @example
   * // Get one AuthzRole
   * const authzRole = await prisma.authzRole.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthzRoleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthzRoleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthzRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthzRoles
   * const authzRoles = await prisma.authzRole.findMany()
   * 
   * // Get first 10 AuthzRoles
   * const authzRoles = await prisma.authzRole.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authzRoleWithIdOnly = await prisma.authzRole.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthzRoleFindManyArgs>(args?: Prisma.SelectSubset<T, AuthzRoleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthzRole.
   * @param {AuthzRoleCreateArgs} args - Arguments to create a AuthzRole.
   * @example
   * // Create one AuthzRole
   * const AuthzRole = await prisma.authzRole.create({
   *   data: {
   *     // ... data to create a AuthzRole
   *   }
   * })
   * 
   */
  create<T extends AuthzRoleCreateArgs>(args: Prisma.SelectSubset<T, AuthzRoleCreateArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthzRoles.
   * @param {AuthzRoleCreateManyArgs} args - Arguments to create many AuthzRoles.
   * @example
   * // Create many AuthzRoles
   * const authzRole = await prisma.authzRole.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthzRoleCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthzRoleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthzRoles and returns the data saved in the database.
   * @param {AuthzRoleCreateManyAndReturnArgs} args - Arguments to create many AuthzRoles.
   * @example
   * // Create many AuthzRoles
   * const authzRole = await prisma.authzRole.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthzRoles and only return the `id`
   * const authzRoleWithIdOnly = await prisma.authzRole.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthzRoleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthzRoleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthzRole.
   * @param {AuthzRoleDeleteArgs} args - Arguments to delete one AuthzRole.
   * @example
   * // Delete one AuthzRole
   * const AuthzRole = await prisma.authzRole.delete({
   *   where: {
   *     // ... filter to delete one AuthzRole
   *   }
   * })
   * 
   */
  delete<T extends AuthzRoleDeleteArgs>(args: Prisma.SelectSubset<T, AuthzRoleDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthzRole.
   * @param {AuthzRoleUpdateArgs} args - Arguments to update one AuthzRole.
   * @example
   * // Update one AuthzRole
   * const authzRole = await prisma.authzRole.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthzRoleUpdateArgs>(args: Prisma.SelectSubset<T, AuthzRoleUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthzRoles.
   * @param {AuthzRoleDeleteManyArgs} args - Arguments to filter AuthzRoles to delete.
   * @example
   * // Delete a few AuthzRoles
   * const { count } = await prisma.authzRole.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthzRoleDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthzRoleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthzRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthzRoles
   * const authzRole = await prisma.authzRole.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthzRoleUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthzRoleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthzRoles and returns the data updated in the database.
   * @param {AuthzRoleUpdateManyAndReturnArgs} args - Arguments to update many AuthzRoles.
   * @example
   * // Update many AuthzRoles
   * const authzRole = await prisma.authzRole.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthzRoles and only return the `id`
   * const authzRoleWithIdOnly = await prisma.authzRole.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthzRoleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthzRoleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthzRole.
   * @param {AuthzRoleUpsertArgs} args - Arguments to update or create a AuthzRole.
   * @example
   * // Update or create a AuthzRole
   * const authzRole = await prisma.authzRole.upsert({
   *   create: {
   *     // ... data to create a AuthzRole
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthzRole we want to update
   *   }
   * })
   */
  upsert<T extends AuthzRoleUpsertArgs>(args: Prisma.SelectSubset<T, AuthzRoleUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthzRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthzRolePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthzRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleCountArgs} args - Arguments to filter AuthzRoles to count.
   * @example
   * // Count the number of AuthzRoles
   * const count = await prisma.authzRole.count({
   *   where: {
   *     // ... the filter for the AuthzRoles we want to count
   *   }
   * })
  **/
  count<T extends AuthzRoleCountArgs>(
    args?: Prisma.Subset<T, AuthzRoleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthzRoleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthzRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthzRoleAggregateArgs>(args: Prisma.Subset<T, AuthzRoleAggregateArgs>): Prisma.PrismaPromise<GetAuthzRoleAggregateType<T>>

  /**
   * Group by AuthzRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzRoleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthzRoleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthzRoleGroupByArgs['orderBy'] }
      : { orderBy?: AuthzRoleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthzRoleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthzRoleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthzRole model
 */
readonly fields: AuthzRoleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthzRole.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthzRoleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthzRole model
 */
export interface AuthzRoleFieldRefs {
  readonly id: Prisma.FieldRef<"AuthzRole", 'String'>
  readonly name: Prisma.FieldRef<"AuthzRole", 'String'>
  readonly permissions: Prisma.FieldRef<"AuthzRole", 'Json'>
  readonly syncedOn: Prisma.FieldRef<"AuthzRole", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AuthzRole findUnique
 */
export type AuthzRoleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter, which AuthzRole to fetch.
   */
  where: Prisma.AuthzRoleWhereUniqueInput
}

/**
 * AuthzRole findUniqueOrThrow
 */
export type AuthzRoleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter, which AuthzRole to fetch.
   */
  where: Prisma.AuthzRoleWhereUniqueInput
}

/**
 * AuthzRole findFirst
 */
export type AuthzRoleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter, which AuthzRole to fetch.
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzRoles to fetch.
   */
  orderBy?: Prisma.AuthzRoleOrderByWithRelationInput | Prisma.AuthzRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthzRoles.
   */
  cursor?: Prisma.AuthzRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzRoles.
   */
  distinct?: Prisma.AuthzRoleScalarFieldEnum | Prisma.AuthzRoleScalarFieldEnum[]
}

/**
 * AuthzRole findFirstOrThrow
 */
export type AuthzRoleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter, which AuthzRole to fetch.
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzRoles to fetch.
   */
  orderBy?: Prisma.AuthzRoleOrderByWithRelationInput | Prisma.AuthzRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthzRoles.
   */
  cursor?: Prisma.AuthzRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzRoles.
   */
  distinct?: Prisma.AuthzRoleScalarFieldEnum | Prisma.AuthzRoleScalarFieldEnum[]
}

/**
 * AuthzRole findMany
 */
export type AuthzRoleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter, which AuthzRoles to fetch.
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzRoles to fetch.
   */
  orderBy?: Prisma.AuthzRoleOrderByWithRelationInput | Prisma.AuthzRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthzRoles.
   */
  cursor?: Prisma.AuthzRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzRoles.
   */
  distinct?: Prisma.AuthzRoleScalarFieldEnum | Prisma.AuthzRoleScalarFieldEnum[]
}

/**
 * AuthzRole create
 */
export type AuthzRoleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * The data needed to create a AuthzRole.
   */
  data: Prisma.XOR<Prisma.AuthzRoleCreateInput, Prisma.AuthzRoleUncheckedCreateInput>
}

/**
 * AuthzRole createMany
 */
export type AuthzRoleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthzRoles.
   */
  data: Prisma.AuthzRoleCreateManyInput | Prisma.AuthzRoleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthzRole createManyAndReturn
 */
export type AuthzRoleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * The data used to create many AuthzRoles.
   */
  data: Prisma.AuthzRoleCreateManyInput | Prisma.AuthzRoleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthzRole update
 */
export type AuthzRoleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * The data needed to update a AuthzRole.
   */
  data: Prisma.XOR<Prisma.AuthzRoleUpdateInput, Prisma.AuthzRoleUncheckedUpdateInput>
  /**
   * Choose, which AuthzRole to update.
   */
  where: Prisma.AuthzRoleWhereUniqueInput
}

/**
 * AuthzRole updateMany
 */
export type AuthzRoleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthzRoles.
   */
  data: Prisma.XOR<Prisma.AuthzRoleUpdateManyMutationInput, Prisma.AuthzRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthzRoles to update
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * Limit how many AuthzRoles to update.
   */
  limit?: number
}

/**
 * AuthzRole updateManyAndReturn
 */
export type AuthzRoleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * The data used to update AuthzRoles.
   */
  data: Prisma.XOR<Prisma.AuthzRoleUpdateManyMutationInput, Prisma.AuthzRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthzRoles to update
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * Limit how many AuthzRoles to update.
   */
  limit?: number
}

/**
 * AuthzRole upsert
 */
export type AuthzRoleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * The filter to search for the AuthzRole to update in case it exists.
   */
  where: Prisma.AuthzRoleWhereUniqueInput
  /**
   * In case the AuthzRole found by the `where` argument doesn't exist, create a new AuthzRole with this data.
   */
  create: Prisma.XOR<Prisma.AuthzRoleCreateInput, Prisma.AuthzRoleUncheckedCreateInput>
  /**
   * In case the AuthzRole was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthzRoleUpdateInput, Prisma.AuthzRoleUncheckedUpdateInput>
}

/**
 * AuthzRole delete
 */
export type AuthzRoleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
  /**
   * Filter which AuthzRole to delete.
   */
  where: Prisma.AuthzRoleWhereUniqueInput
}

/**
 * AuthzRole deleteMany
 */
export type AuthzRoleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthzRoles to delete
   */
  where?: Prisma.AuthzRoleWhereInput
  /**
   * Limit how many AuthzRoles to delete.
   */
  limit?: number
}

/**
 * AuthzRole without action
 */
export type AuthzRoleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzRole
   */
  select?: Prisma.AuthzRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzRole
   */
  omit?: Prisma.AuthzRoleOmit<ExtArgs> | null
}
