
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthzAccess` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AuthzAccess
 * 
 */
export type AuthzAccessModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthzAccessPayload>

export type AggregateAuthzAccess = {
  _count: AuthzAccessCountAggregateOutputType | null
  _min: AuthzAccessMinAggregateOutputType | null
  _max: AuthzAccessMaxAggregateOutputType | null
}

export type AuthzAccessMinAggregateOutputType = {
  id: string | null
  accountId: string | null
  articleId: string | null
  projectId: string | null
  roleId: string | null
  createdOn: Date | null
  status: string | null
}

export type AuthzAccessMaxAggregateOutputType = {
  id: string | null
  accountId: string | null
  articleId: string | null
  projectId: string | null
  roleId: string | null
  createdOn: Date | null
  status: string | null
}

export type AuthzAccessCountAggregateOutputType = {
  id: number
  accountId: number
  articleId: number
  projectId: number
  roleId: number
  createdOn: number
  status: number
  _all: number
}


export type AuthzAccessMinAggregateInputType = {
  id?: true
  accountId?: true
  articleId?: true
  projectId?: true
  roleId?: true
  createdOn?: true
  status?: true
}

export type AuthzAccessMaxAggregateInputType = {
  id?: true
  accountId?: true
  articleId?: true
  projectId?: true
  roleId?: true
  createdOn?: true
  status?: true
}

export type AuthzAccessCountAggregateInputType = {
  id?: true
  accountId?: true
  articleId?: true
  projectId?: true
  roleId?: true
  createdOn?: true
  status?: true
  _all?: true
}

export type AuthzAccessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthzAccess to aggregate.
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzAccesses to fetch.
   */
  orderBy?: Prisma.AuthzAccessOrderByWithRelationInput | Prisma.AuthzAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthzAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthzAccesses
  **/
  _count?: true | AuthzAccessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthzAccessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthzAccessMaxAggregateInputType
}

export type GetAuthzAccessAggregateType<T extends AuthzAccessAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthzAccess]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthzAccess[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthzAccess[P]>
}




export type AuthzAccessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthzAccessWhereInput
  orderBy?: Prisma.AuthzAccessOrderByWithAggregationInput | Prisma.AuthzAccessOrderByWithAggregationInput[]
  by: Prisma.AuthzAccessScalarFieldEnum[] | Prisma.AuthzAccessScalarFieldEnum
  having?: Prisma.AuthzAccessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthzAccessCountAggregateInputType | true
  _min?: AuthzAccessMinAggregateInputType
  _max?: AuthzAccessMaxAggregateInputType
}

export type AuthzAccessGroupByOutputType = {
  id: string
  accountId: string
  articleId: string | null
  projectId: string | null
  roleId: string
  createdOn: Date
  status: string
  _count: AuthzAccessCountAggregateOutputType | null
  _min: AuthzAccessMinAggregateOutputType | null
  _max: AuthzAccessMaxAggregateOutputType | null
}

export type GetAuthzAccessGroupByPayload<T extends AuthzAccessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthzAccessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthzAccessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthzAccessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthzAccessGroupByOutputType[P]>
      }
    >
  >



export type AuthzAccessWhereInput = {
  AND?: Prisma.AuthzAccessWhereInput | Prisma.AuthzAccessWhereInput[]
  OR?: Prisma.AuthzAccessWhereInput[]
  NOT?: Prisma.AuthzAccessWhereInput | Prisma.AuthzAccessWhereInput[]
  id?: Prisma.StringFilter<"AuthzAccess"> | string
  accountId?: Prisma.StringFilter<"AuthzAccess"> | string
  articleId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  projectId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  roleId?: Prisma.StringFilter<"AuthzAccess"> | string
  createdOn?: Prisma.DateTimeFilter<"AuthzAccess"> | Date | string
  status?: Prisma.StringFilter<"AuthzAccess"> | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  article?: Prisma.XOR<Prisma.ArticleNullableScalarRelationFilter, Prisma.ArticleWhereInput> | null
}

export type AuthzAccessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  articleId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  roleId?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  account?: Prisma.AccountOrderByWithRelationInput
  article?: Prisma.ArticleOrderByWithRelationInput
}

export type AuthzAccessWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuthzAccessWhereInput | Prisma.AuthzAccessWhereInput[]
  OR?: Prisma.AuthzAccessWhereInput[]
  NOT?: Prisma.AuthzAccessWhereInput | Prisma.AuthzAccessWhereInput[]
  accountId?: Prisma.StringFilter<"AuthzAccess"> | string
  articleId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  projectId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  roleId?: Prisma.StringFilter<"AuthzAccess"> | string
  createdOn?: Prisma.DateTimeFilter<"AuthzAccess"> | Date | string
  status?: Prisma.StringFilter<"AuthzAccess"> | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  article?: Prisma.XOR<Prisma.ArticleNullableScalarRelationFilter, Prisma.ArticleWhereInput> | null
}, "id">

export type AuthzAccessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  articleId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  roleId?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.AuthzAccessCountOrderByAggregateInput
  _max?: Prisma.AuthzAccessMaxOrderByAggregateInput
  _min?: Prisma.AuthzAccessMinOrderByAggregateInput
}

export type AuthzAccessScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthzAccessScalarWhereWithAggregatesInput | Prisma.AuthzAccessScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthzAccessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthzAccessScalarWhereWithAggregatesInput | Prisma.AuthzAccessScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthzAccess"> | string
  accountId?: Prisma.StringWithAggregatesFilter<"AuthzAccess"> | string
  articleId?: Prisma.StringNullableWithAggregatesFilter<"AuthzAccess"> | string | null
  projectId?: Prisma.StringNullableWithAggregatesFilter<"AuthzAccess"> | string | null
  roleId?: Prisma.StringWithAggregatesFilter<"AuthzAccess"> | string
  createdOn?: Prisma.DateTimeWithAggregatesFilter<"AuthzAccess"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"AuthzAccess"> | string
}

export type AuthzAccessCreateInput = {
  id?: string
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
  account: Prisma.AccountCreateNestedOneWithoutAuthzAccessInput
  article?: Prisma.ArticleCreateNestedOneWithoutAuthzAccessInput
}

export type AuthzAccessUncheckedCreateInput = {
  id?: string
  accountId: string
  articleId?: string | null
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.AccountUpdateOneRequiredWithoutAuthzAccessNestedInput
  article?: Prisma.ArticleUpdateOneWithoutAuthzAccessNestedInput
}

export type AuthzAccessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessCreateManyInput = {
  id?: string
  accountId: string
  articleId?: string | null
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessListRelationFilter = {
  every?: Prisma.AuthzAccessWhereInput
  some?: Prisma.AuthzAccessWhereInput
  none?: Prisma.AuthzAccessWhereInput
}

export type AuthzAccessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AuthzAccessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type AuthzAccessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type AuthzAccessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  articleId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type AuthzAccessCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput> | Prisma.AuthzAccessCreateWithoutAccountInput[] | Prisma.AuthzAccessUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutAccountInput | Prisma.AuthzAccessCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.AuthzAccessCreateManyAccountInputEnvelope
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
}

export type AuthzAccessUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput> | Prisma.AuthzAccessCreateWithoutAccountInput[] | Prisma.AuthzAccessUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutAccountInput | Prisma.AuthzAccessCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.AuthzAccessCreateManyAccountInputEnvelope
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
}

export type AuthzAccessUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput> | Prisma.AuthzAccessCreateWithoutAccountInput[] | Prisma.AuthzAccessUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutAccountInput | Prisma.AuthzAccessCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.AuthzAccessUpsertWithWhereUniqueWithoutAccountInput | Prisma.AuthzAccessUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.AuthzAccessCreateManyAccountInputEnvelope
  set?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  disconnect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  delete?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  update?: Prisma.AuthzAccessUpdateWithWhereUniqueWithoutAccountInput | Prisma.AuthzAccessUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.AuthzAccessUpdateManyWithWhereWithoutAccountInput | Prisma.AuthzAccessUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
}

export type AuthzAccessUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput> | Prisma.AuthzAccessCreateWithoutAccountInput[] | Prisma.AuthzAccessUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutAccountInput | Prisma.AuthzAccessCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.AuthzAccessUpsertWithWhereUniqueWithoutAccountInput | Prisma.AuthzAccessUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.AuthzAccessCreateManyAccountInputEnvelope
  set?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  disconnect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  delete?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  update?: Prisma.AuthzAccessUpdateWithWhereUniqueWithoutAccountInput | Prisma.AuthzAccessUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.AuthzAccessUpdateManyWithWhereWithoutAccountInput | Prisma.AuthzAccessUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
}

export type AuthzAccessCreateNestedManyWithoutArticleInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput> | Prisma.AuthzAccessCreateWithoutArticleInput[] | Prisma.AuthzAccessUncheckedCreateWithoutArticleInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutArticleInput | Prisma.AuthzAccessCreateOrConnectWithoutArticleInput[]
  createMany?: Prisma.AuthzAccessCreateManyArticleInputEnvelope
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
}

export type AuthzAccessUncheckedCreateNestedManyWithoutArticleInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput> | Prisma.AuthzAccessCreateWithoutArticleInput[] | Prisma.AuthzAccessUncheckedCreateWithoutArticleInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutArticleInput | Prisma.AuthzAccessCreateOrConnectWithoutArticleInput[]
  createMany?: Prisma.AuthzAccessCreateManyArticleInputEnvelope
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
}

export type AuthzAccessUpdateManyWithoutArticleNestedInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput> | Prisma.AuthzAccessCreateWithoutArticleInput[] | Prisma.AuthzAccessUncheckedCreateWithoutArticleInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutArticleInput | Prisma.AuthzAccessCreateOrConnectWithoutArticleInput[]
  upsert?: Prisma.AuthzAccessUpsertWithWhereUniqueWithoutArticleInput | Prisma.AuthzAccessUpsertWithWhereUniqueWithoutArticleInput[]
  createMany?: Prisma.AuthzAccessCreateManyArticleInputEnvelope
  set?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  disconnect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  delete?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  update?: Prisma.AuthzAccessUpdateWithWhereUniqueWithoutArticleInput | Prisma.AuthzAccessUpdateWithWhereUniqueWithoutArticleInput[]
  updateMany?: Prisma.AuthzAccessUpdateManyWithWhereWithoutArticleInput | Prisma.AuthzAccessUpdateManyWithWhereWithoutArticleInput[]
  deleteMany?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
}

export type AuthzAccessUncheckedUpdateManyWithoutArticleNestedInput = {
  create?: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput> | Prisma.AuthzAccessCreateWithoutArticleInput[] | Prisma.AuthzAccessUncheckedCreateWithoutArticleInput[]
  connectOrCreate?: Prisma.AuthzAccessCreateOrConnectWithoutArticleInput | Prisma.AuthzAccessCreateOrConnectWithoutArticleInput[]
  upsert?: Prisma.AuthzAccessUpsertWithWhereUniqueWithoutArticleInput | Prisma.AuthzAccessUpsertWithWhereUniqueWithoutArticleInput[]
  createMany?: Prisma.AuthzAccessCreateManyArticleInputEnvelope
  set?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  disconnect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  delete?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  connect?: Prisma.AuthzAccessWhereUniqueInput | Prisma.AuthzAccessWhereUniqueInput[]
  update?: Prisma.AuthzAccessUpdateWithWhereUniqueWithoutArticleInput | Prisma.AuthzAccessUpdateWithWhereUniqueWithoutArticleInput[]
  updateMany?: Prisma.AuthzAccessUpdateManyWithWhereWithoutArticleInput | Prisma.AuthzAccessUpdateManyWithWhereWithoutArticleInput[]
  deleteMany?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
}

export type AuthzAccessCreateWithoutAccountInput = {
  id?: string
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
  article?: Prisma.ArticleCreateNestedOneWithoutAuthzAccessInput
}

export type AuthzAccessUncheckedCreateWithoutAccountInput = {
  id?: string
  articleId?: string | null
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessCreateOrConnectWithoutAccountInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput>
}

export type AuthzAccessCreateManyAccountInputEnvelope = {
  data: Prisma.AuthzAccessCreateManyAccountInput | Prisma.AuthzAccessCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type AuthzAccessUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthzAccessUpdateWithoutAccountInput, Prisma.AuthzAccessUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.AuthzAccessCreateWithoutAccountInput, Prisma.AuthzAccessUncheckedCreateWithoutAccountInput>
}

export type AuthzAccessUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthzAccessUpdateWithoutAccountInput, Prisma.AuthzAccessUncheckedUpdateWithoutAccountInput>
}

export type AuthzAccessUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.AuthzAccessScalarWhereInput
  data: Prisma.XOR<Prisma.AuthzAccessUpdateManyMutationInput, Prisma.AuthzAccessUncheckedUpdateManyWithoutAccountInput>
}

export type AuthzAccessScalarWhereInput = {
  AND?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
  OR?: Prisma.AuthzAccessScalarWhereInput[]
  NOT?: Prisma.AuthzAccessScalarWhereInput | Prisma.AuthzAccessScalarWhereInput[]
  id?: Prisma.StringFilter<"AuthzAccess"> | string
  accountId?: Prisma.StringFilter<"AuthzAccess"> | string
  articleId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  projectId?: Prisma.StringNullableFilter<"AuthzAccess"> | string | null
  roleId?: Prisma.StringFilter<"AuthzAccess"> | string
  createdOn?: Prisma.DateTimeFilter<"AuthzAccess"> | Date | string
  status?: Prisma.StringFilter<"AuthzAccess"> | string
}

export type AuthzAccessCreateWithoutArticleInput = {
  id?: string
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
  account: Prisma.AccountCreateNestedOneWithoutAuthzAccessInput
}

export type AuthzAccessUncheckedCreateWithoutArticleInput = {
  id?: string
  accountId: string
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessCreateOrConnectWithoutArticleInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput>
}

export type AuthzAccessCreateManyArticleInputEnvelope = {
  data: Prisma.AuthzAccessCreateManyArticleInput | Prisma.AuthzAccessCreateManyArticleInput[]
  skipDuplicates?: boolean
}

export type AuthzAccessUpsertWithWhereUniqueWithoutArticleInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthzAccessUpdateWithoutArticleInput, Prisma.AuthzAccessUncheckedUpdateWithoutArticleInput>
  create: Prisma.XOR<Prisma.AuthzAccessCreateWithoutArticleInput, Prisma.AuthzAccessUncheckedCreateWithoutArticleInput>
}

export type AuthzAccessUpdateWithWhereUniqueWithoutArticleInput = {
  where: Prisma.AuthzAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthzAccessUpdateWithoutArticleInput, Prisma.AuthzAccessUncheckedUpdateWithoutArticleInput>
}

export type AuthzAccessUpdateManyWithWhereWithoutArticleInput = {
  where: Prisma.AuthzAccessScalarWhereInput
  data: Prisma.XOR<Prisma.AuthzAccessUpdateManyMutationInput, Prisma.AuthzAccessUncheckedUpdateManyWithoutArticleInput>
}

export type AuthzAccessCreateManyAccountInput = {
  id?: string
  articleId?: string | null
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  article?: Prisma.ArticleUpdateOneWithoutAuthzAccessNestedInput
}

export type AuthzAccessUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  articleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessCreateManyArticleInput = {
  id?: string
  accountId: string
  projectId?: string | null
  roleId: string
  createdOn?: Date | string
  status?: string
}

export type AuthzAccessUpdateWithoutArticleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  account?: Prisma.AccountUpdateOneRequiredWithoutAuthzAccessNestedInput
}

export type AuthzAccessUncheckedUpdateWithoutArticleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AuthzAccessUncheckedUpdateManyWithoutArticleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AuthzAccessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  articleId?: boolean
  projectId?: boolean
  roleId?: boolean
  createdOn?: boolean
  status?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}, ExtArgs["result"]["authzAccess"]>

export type AuthzAccessSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  articleId?: boolean
  projectId?: boolean
  roleId?: boolean
  createdOn?: boolean
  status?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}, ExtArgs["result"]["authzAccess"]>

export type AuthzAccessSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  articleId?: boolean
  projectId?: boolean
  roleId?: boolean
  createdOn?: boolean
  status?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}, ExtArgs["result"]["authzAccess"]>

export type AuthzAccessSelectScalar = {
  id?: boolean
  accountId?: boolean
  articleId?: boolean
  projectId?: boolean
  roleId?: boolean
  createdOn?: boolean
  status?: boolean
}

export type AuthzAccessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accountId" | "articleId" | "projectId" | "roleId" | "createdOn" | "status", ExtArgs["result"]["authzAccess"]>
export type AuthzAccessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}
export type AuthzAccessIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}
export type AuthzAccessIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  article?: boolean | Prisma.AuthzAccess$articleArgs<ExtArgs>
}

export type $AuthzAccessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthzAccess"
  objects: {
    account: Prisma.$AccountPayload<ExtArgs>
    article: Prisma.$ArticlePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accountId: string
    articleId: string | null
    projectId: string | null
    roleId: string
    createdOn: Date
    status: string
  }, ExtArgs["result"]["authzAccess"]>
  composites: {}
}

export type AuthzAccessGetPayload<S extends boolean | null | undefined | AuthzAccessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload, S>

export type AuthzAccessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthzAccessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthzAccessCountAggregateInputType | true
  }

export interface AuthzAccessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthzAccess'], meta: { name: 'AuthzAccess' } }
  /**
   * Find zero or one AuthzAccess that matches the filter.
   * @param {AuthzAccessFindUniqueArgs} args - Arguments to find a AuthzAccess
   * @example
   * // Get one AuthzAccess
   * const authzAccess = await prisma.authzAccess.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthzAccessFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthzAccessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthzAccess that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthzAccessFindUniqueOrThrowArgs} args - Arguments to find a AuthzAccess
   * @example
   * // Get one AuthzAccess
   * const authzAccess = await prisma.authzAccess.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthzAccessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthzAccessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthzAccess that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessFindFirstArgs} args - Arguments to find a AuthzAccess
   * @example
   * // Get one AuthzAccess
   * const authzAccess = await prisma.authzAccess.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthzAccessFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthzAccessFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthzAccess that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessFindFirstOrThrowArgs} args - Arguments to find a AuthzAccess
   * @example
   * // Get one AuthzAccess
   * const authzAccess = await prisma.authzAccess.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthzAccessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthzAccessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthzAccesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthzAccesses
   * const authzAccesses = await prisma.authzAccess.findMany()
   * 
   * // Get first 10 AuthzAccesses
   * const authzAccesses = await prisma.authzAccess.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authzAccessWithIdOnly = await prisma.authzAccess.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthzAccessFindManyArgs>(args?: Prisma.SelectSubset<T, AuthzAccessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthzAccess.
   * @param {AuthzAccessCreateArgs} args - Arguments to create a AuthzAccess.
   * @example
   * // Create one AuthzAccess
   * const AuthzAccess = await prisma.authzAccess.create({
   *   data: {
   *     // ... data to create a AuthzAccess
   *   }
   * })
   * 
   */
  create<T extends AuthzAccessCreateArgs>(args: Prisma.SelectSubset<T, AuthzAccessCreateArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthzAccesses.
   * @param {AuthzAccessCreateManyArgs} args - Arguments to create many AuthzAccesses.
   * @example
   * // Create many AuthzAccesses
   * const authzAccess = await prisma.authzAccess.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthzAccessCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthzAccessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthzAccesses and returns the data saved in the database.
   * @param {AuthzAccessCreateManyAndReturnArgs} args - Arguments to create many AuthzAccesses.
   * @example
   * // Create many AuthzAccesses
   * const authzAccess = await prisma.authzAccess.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthzAccesses and only return the `id`
   * const authzAccessWithIdOnly = await prisma.authzAccess.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthzAccessCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthzAccessCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthzAccess.
   * @param {AuthzAccessDeleteArgs} args - Arguments to delete one AuthzAccess.
   * @example
   * // Delete one AuthzAccess
   * const AuthzAccess = await prisma.authzAccess.delete({
   *   where: {
   *     // ... filter to delete one AuthzAccess
   *   }
   * })
   * 
   */
  delete<T extends AuthzAccessDeleteArgs>(args: Prisma.SelectSubset<T, AuthzAccessDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthzAccess.
   * @param {AuthzAccessUpdateArgs} args - Arguments to update one AuthzAccess.
   * @example
   * // Update one AuthzAccess
   * const authzAccess = await prisma.authzAccess.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthzAccessUpdateArgs>(args: Prisma.SelectSubset<T, AuthzAccessUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthzAccesses.
   * @param {AuthzAccessDeleteManyArgs} args - Arguments to filter AuthzAccesses to delete.
   * @example
   * // Delete a few AuthzAccesses
   * const { count } = await prisma.authzAccess.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthzAccessDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthzAccessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthzAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthzAccesses
   * const authzAccess = await prisma.authzAccess.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthzAccessUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthzAccessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthzAccesses and returns the data updated in the database.
   * @param {AuthzAccessUpdateManyAndReturnArgs} args - Arguments to update many AuthzAccesses.
   * @example
   * // Update many AuthzAccesses
   * const authzAccess = await prisma.authzAccess.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthzAccesses and only return the `id`
   * const authzAccessWithIdOnly = await prisma.authzAccess.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthzAccessUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthzAccessUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthzAccess.
   * @param {AuthzAccessUpsertArgs} args - Arguments to update or create a AuthzAccess.
   * @example
   * // Update or create a AuthzAccess
   * const authzAccess = await prisma.authzAccess.upsert({
   *   create: {
   *     // ... data to create a AuthzAccess
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthzAccess we want to update
   *   }
   * })
   */
  upsert<T extends AuthzAccessUpsertArgs>(args: Prisma.SelectSubset<T, AuthzAccessUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthzAccessClient<runtime.Types.Result.GetResult<Prisma.$AuthzAccessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthzAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessCountArgs} args - Arguments to filter AuthzAccesses to count.
   * @example
   * // Count the number of AuthzAccesses
   * const count = await prisma.authzAccess.count({
   *   where: {
   *     // ... the filter for the AuthzAccesses we want to count
   *   }
   * })
  **/
  count<T extends AuthzAccessCountArgs>(
    args?: Prisma.Subset<T, AuthzAccessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthzAccessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthzAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthzAccessAggregateArgs>(args: Prisma.Subset<T, AuthzAccessAggregateArgs>): Prisma.PrismaPromise<GetAuthzAccessAggregateType<T>>

  /**
   * Group by AuthzAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthzAccessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthzAccessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthzAccessGroupByArgs['orderBy'] }
      : { orderBy?: AuthzAccessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthzAccessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthzAccessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthzAccess model
 */
readonly fields: AuthzAccessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthzAccess.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthzAccessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  article<T extends Prisma.AuthzAccess$articleArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthzAccess$articleArgs<ExtArgs>>): Prisma.Prisma__ArticleClient<runtime.Types.Result.GetResult<Prisma.$ArticlePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthzAccess model
 */
export interface AuthzAccessFieldRefs {
  readonly id: Prisma.FieldRef<"AuthzAccess", 'String'>
  readonly accountId: Prisma.FieldRef<"AuthzAccess", 'String'>
  readonly articleId: Prisma.FieldRef<"AuthzAccess", 'String'>
  readonly projectId: Prisma.FieldRef<"AuthzAccess", 'String'>
  readonly roleId: Prisma.FieldRef<"AuthzAccess", 'String'>
  readonly createdOn: Prisma.FieldRef<"AuthzAccess", 'DateTime'>
  readonly status: Prisma.FieldRef<"AuthzAccess", 'String'>
}
    

// Custom InputTypes
/**
 * AuthzAccess findUnique
 */
export type AuthzAccessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter, which AuthzAccess to fetch.
   */
  where: Prisma.AuthzAccessWhereUniqueInput
}

/**
 * AuthzAccess findUniqueOrThrow
 */
export type AuthzAccessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter, which AuthzAccess to fetch.
   */
  where: Prisma.AuthzAccessWhereUniqueInput
}

/**
 * AuthzAccess findFirst
 */
export type AuthzAccessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter, which AuthzAccess to fetch.
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzAccesses to fetch.
   */
  orderBy?: Prisma.AuthzAccessOrderByWithRelationInput | Prisma.AuthzAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthzAccesses.
   */
  cursor?: Prisma.AuthzAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzAccesses.
   */
  distinct?: Prisma.AuthzAccessScalarFieldEnum | Prisma.AuthzAccessScalarFieldEnum[]
}

/**
 * AuthzAccess findFirstOrThrow
 */
export type AuthzAccessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter, which AuthzAccess to fetch.
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzAccesses to fetch.
   */
  orderBy?: Prisma.AuthzAccessOrderByWithRelationInput | Prisma.AuthzAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthzAccesses.
   */
  cursor?: Prisma.AuthzAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzAccesses.
   */
  distinct?: Prisma.AuthzAccessScalarFieldEnum | Prisma.AuthzAccessScalarFieldEnum[]
}

/**
 * AuthzAccess findMany
 */
export type AuthzAccessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter, which AuthzAccesses to fetch.
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthzAccesses to fetch.
   */
  orderBy?: Prisma.AuthzAccessOrderByWithRelationInput | Prisma.AuthzAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthzAccesses.
   */
  cursor?: Prisma.AuthzAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthzAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthzAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthzAccesses.
   */
  distinct?: Prisma.AuthzAccessScalarFieldEnum | Prisma.AuthzAccessScalarFieldEnum[]
}

/**
 * AuthzAccess create
 */
export type AuthzAccessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthzAccess.
   */
  data: Prisma.XOR<Prisma.AuthzAccessCreateInput, Prisma.AuthzAccessUncheckedCreateInput>
}

/**
 * AuthzAccess createMany
 */
export type AuthzAccessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthzAccesses.
   */
  data: Prisma.AuthzAccessCreateManyInput | Prisma.AuthzAccessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthzAccess createManyAndReturn
 */
export type AuthzAccessCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * The data used to create many AuthzAccesses.
   */
  data: Prisma.AuthzAccessCreateManyInput | Prisma.AuthzAccessCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuthzAccess update
 */
export type AuthzAccessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthzAccess.
   */
  data: Prisma.XOR<Prisma.AuthzAccessUpdateInput, Prisma.AuthzAccessUncheckedUpdateInput>
  /**
   * Choose, which AuthzAccess to update.
   */
  where: Prisma.AuthzAccessWhereUniqueInput
}

/**
 * AuthzAccess updateMany
 */
export type AuthzAccessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthzAccesses.
   */
  data: Prisma.XOR<Prisma.AuthzAccessUpdateManyMutationInput, Prisma.AuthzAccessUncheckedUpdateManyInput>
  /**
   * Filter which AuthzAccesses to update
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * Limit how many AuthzAccesses to update.
   */
  limit?: number
}

/**
 * AuthzAccess updateManyAndReturn
 */
export type AuthzAccessUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * The data used to update AuthzAccesses.
   */
  data: Prisma.XOR<Prisma.AuthzAccessUpdateManyMutationInput, Prisma.AuthzAccessUncheckedUpdateManyInput>
  /**
   * Filter which AuthzAccesses to update
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * Limit how many AuthzAccesses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuthzAccess upsert
 */
export type AuthzAccessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthzAccess to update in case it exists.
   */
  where: Prisma.AuthzAccessWhereUniqueInput
  /**
   * In case the AuthzAccess found by the `where` argument doesn't exist, create a new AuthzAccess with this data.
   */
  create: Prisma.XOR<Prisma.AuthzAccessCreateInput, Prisma.AuthzAccessUncheckedCreateInput>
  /**
   * In case the AuthzAccess was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthzAccessUpdateInput, Prisma.AuthzAccessUncheckedUpdateInput>
}

/**
 * AuthzAccess delete
 */
export type AuthzAccessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
  /**
   * Filter which AuthzAccess to delete.
   */
  where: Prisma.AuthzAccessWhereUniqueInput
}

/**
 * AuthzAccess deleteMany
 */
export type AuthzAccessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthzAccesses to delete
   */
  where?: Prisma.AuthzAccessWhereInput
  /**
   * Limit how many AuthzAccesses to delete.
   */
  limit?: number
}

/**
 * AuthzAccess.article
 */
export type AuthzAccess$articleArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Article
   */
  select?: Prisma.ArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Article
   */
  omit?: Prisma.ArticleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArticleInclude<ExtArgs> | null
  where?: Prisma.ArticleWhereInput
}

/**
 * AuthzAccess without action
 */
export type AuthzAccessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthzAccess
   */
  select?: Prisma.AuthzAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthzAccess
   */
  omit?: Prisma.AuthzAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthzAccessInclude<ExtArgs> | null
}
